# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    groups:
      python-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "major"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge configuration
    auto-merge: true
    automerge-options:
      merge-method: "squash"
      update-types:
        - "minor"
        - "patch"
      require-all-status-checks: true

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "npm"
      include: "scope"
    groups:
      javascript-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "major"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge configuration
    auto-merge: true
    automerge-options:
      merge-method: "squash"
      update-types:
        - "minor"
        - "patch"
      require-all-status-checks: true

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "major"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge configuration
    auto-merge: true
    automerge-options:
      merge-method: "squash"
      update-types:
        - "minor"
        - "patch"
      require-all-status-checks: true
