repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
    - id: gitleaks
-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: bash -c 'cd frontend && npx prettier --write .'
        language: system
        pass_filenames: false
        types: [file]
        files: \.(js|ts|jsx|tsx|css|scss|json|md|html)$
