name: 'Auto Assign PR'
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/pr-auto-assign.yml' # Only needed if you use something other than .github/auto_assign.yml
