name: Tests and Verification

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8 black pytest pre-commit

      - name: Run Black
        run: |
          black --check --line-length 100 backend/
        continue-on-error: true

      - name: Lint with flake8
        run: |
          flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      - name: Run Django tests
        run: |
          cd backend
          python manage.py test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint src/
        continue-on-error: true

      - name: Run Prettier check
        run: |
          cd frontend
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,scss,json}"

      - name: Run React tests
        run: |
          cd frontend
          npm test -- --watchAll=false --passWithNoTests
